server:
  port: 9003

spring:
  security:
    oauth2:
      client:
        registration:
          comment-service:
            client-id: comment-service
            client-secret: comment-service
            client-name: comment
            provider: my-oauth-provider
            scope: all
            redirect-uri-template: http://localhost:9003/login/oauth2/code/callback
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          my-oauth-provider:
            authorization-uri: http://localhost:9000/oauth/authorize
            token-uri: http://localhost:9000/oauth/token
logging:
  level:
    root: debug