server:
  port: 18002
spring:
  # 服务名称
  application:
    name: user-data
  # MongoDB 配置
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/movie
  # Redis 配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
  # RabbitMQ 配置
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  # Consul服务注册中心
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
        service-name: user-data
        health-check-timeout: 15s
# 权限配置
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://${AUTH_CENTER_HOST:localhost}:${AUTH_CENTER_PORT:18001}/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}
# 日志配置
logging:
  file: logs/user-data.log