server:
  port: 9000
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/movie
  redis:
    host: localhost
    port: 6379
    database: 0
# OAuth2 配置
security:
  oauth2:
    client:
      client-id: record-service
      client-secret: record-service
      scope: read,write,all
      auto-approve-scopes: '.*'
logging:
  level:
    org.springframework.security: DEBUG
