spring:
  application:
    name: auth-center
  profiles:
    active: dev
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        # 使用IP地址进行注册，而不是主机名
        prefer-ip-address: true
        service-name: auth-center
  #        health-check-path: ${server.serlvet.context-path}/health
  #        tags: ${server.serlvet.context-path}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 0
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/movie
  freemarker:
    request-context-attribute: request
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest


#security:
#  ignored:
#    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,/static/**,
#    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
#    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,/druid/**,
#    /oauth/deleteToken, /backReferer

server:
  port: 18001
  tomcat:
    max-threads: 500
    min-spare-threads: 50
#  servlet:
#    context-path: /auth

logging:
  file: logs/auth-center.log


# Ribbon超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

# 开启熔断器超时检测
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true


